export interface Funcionario {
    id?:string;
    admissao?:string;
    cargo?:string;
    cpf?:string;
    email?:string;
    endereco?:{
      logradouro?:string;
      numero?:string;
      apto?:string;
      bairro?:string;
      cidade?:string;
      estado?:string;
      pais?:string;
    };
    localtrab?:{
      logradouro?:string;
      numero?:string;
      bairro?:string;
      cidade?:string;
      estado?:string;
      pais?:string;
    };
    matricula?:string;
    nascimento?:string;
    nome?:string;
    telefone?:string;
  }